# Site settings
title: Ananya Ipsita
email: aipsita@purdue.edu
description: Academic webpage of Ananya Ipsita
baseurl: ""
url: ""

# Google analytics ID: Uncomment and your own, if you like
# google_analytics: XX
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
  Ananya Ipsita<br/>
  Ph.D. Candidate<br/>
  Purdue University

location: >
  Mechanical Engineering Building, Room 3164<br/>
  585 Purdue Mall<br/>
  West Lafayette, IN 47907

contact: >
  <a href="mailto:aipsita@purdue.edu" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Ananya via email</a> <br/>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: research
  - name: teaching
  - name: publications
  - name: others

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins: ["jekyll/scholar"]

scholar:
  last_name: Doe
  first_name: [John]

  style: citesty
  locale: en

  source: /assets/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
